name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "build psptoolchain and remotejoy"
        id: latest_tag
        run: |
         git clone https://github.com/pspdev/psptoolchain.git
         cd psptoolchain
         sudo mkdir -p /usr/local/pspdev
         echo "PSPDEV=/usr/local/pspdev" >> $PSPDEV
         sudo chown -R $USER: $PSPDEV
         echo "$PATH=$PATH:/usr/local/pspdev/bin" >> $PATH
         sudo bash ./prepare-debian-ubuntu.sh
         sudo apt install libgpgme-dev
         sudo bash ./toolchain-sudo.sh
         cd ../ 
         git clone https://github.com/pspdev/psplinkusb.git
         cd psplinkusb
         make all
         cd ../
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
         name: Artifacts
         path: ./
